# TODO: default should be merkle and required IGP or other way around?
defaultHook:
  type: merkleTreeHook
defaultIsm:
  type: merkleRootMultisigIsm
  threshold: 1
  validators:
    - "0xa51e4054dd6fc5ac01e6bbf2434da8872377c7e6"
owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
proxyAdmin:
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
requiredHook:
  beneficiary: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  oracleConfig:
    dymension:
      gasPrice: "1"
      # TODO: check rate
      tokenExchangeRate: "1"
  oracleKey: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  overhead:
    dymension: 4000000
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  type: interchainGasPaymaster
