# TODO: default should be merkle and required IGP or other way around?
defaultHook:
  type: merkleTreeHook
defaultIsm:
  type: merkleRootMultisigIsm
  threshold: 1
  validators:
    - "0x543298B2CfB5dBc7C811133cF2EB25adb5e8ACC0"
owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
proxyAdmin:
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
requiredHook:
  beneficiary: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  oracleConfig:
    dymension:
      gasPrice: "1"
      tokenExchangeRate: "1"
  oracleKey: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  overhead:
    dymension: 4000000
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  type: interchainGasPaymaster
